# Wav2Vec2 Swahili ASR - Local Evaluation (Mac)
WER & CER Evaluation

In [9]:
import torch
print(torch.__version__)

2.2.2

In [10]:
# Install dependencies (run once)
# !pip install transformers datasets evaluate jiwer torch torchaudio

In [ ]:
import os
import re
import torch
import torchaudio
import pandas as pd
import numpy as np
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
import evaluate

# Use CPU - MPS has compatibility issues with wav2vec2
device = torch.device("cpu")
print(f"Using device: {device}")
print(f"PyTorch version: {torch.__version__}")

In [12]:
# Configuration
repo_name = 'jkhyjkhy/wav2vec2-large-xlsr-sw-ASR'

# Local paths
BASE = '/Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23'
CSV = f'{BASE}/manifest_sw_14_0_delta.csv'
AUDIO_DIR = f'{BASE}/cleaned_sw_audio_14_0_delta'

print(f"Base path: {BASE}")
print(f"CSV path: {CSV}")
print(f"Audio dir: {AUDIO_DIR}")

Base path: /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23
CSV path: /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/manifest_sw_14_0_delta.csv
Audio dir: /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta

In [13]:
# Load dataset
df = pd.read_csv(CSV)
df["wav_path"] = df["wav_path"].apply(lambda p: os.path.join(AUDIO_DIR, os.path.basename(p)))
print(f"Total samples in dataset: {len(df)}")
df.head()

Total samples in dataset: 270

,wav_path,duration,transcript
0,/Users/annette/Desktop/automatic_speech_recogn...,3.252,Ugongwa wa kupinda shingo
1,/Users/annette/Desktop/automatic_speech_recogn...,5.979,Dalili ya ugonjwa wa miguu na midomo ni mnyama...
2,/Users/annette/Desktop/automatic_speech_recogn...,4.046,Wanyama walioathirika na ugonjwa wa ukurutu wa...
3,/Users/annette/Desktop/automatic_speech_recogn...,7.815,Hata hivyo maelfu ya watu waliojitokeza kumsik...
4,/Users/annette/Desktop/automatic_speech_recogn...,7.174,Marais Uhuru Kenyata wa Kenya Yoweri Museveni ...

In [14]:
# Text preprocessing function
def remove_special_characters(text):
    chars_to_ignore_regex = '[\,\?\.\'\!\-\;\:\"\(\)]'
    return re.sub(chars_to_ignore_regex, '', text).lower() + " "

# Apply preprocessing to dataframe
df["transcript"] = df["transcript"].apply(remove_special_characters)
print(f"Preprocessed {len(df)} samples")

Preprocessed 270 samples

In [15]:
# Load model and processor from HuggingFace
print("Loading model and processor...")
processor = Wav2Vec2Processor.from_pretrained(repo_name)
model = Wav2Vec2ForCTC.from_pretrained(repo_name)
model.to(device)
model.eval()
print("Model loaded successfully!")

Loading model and processor...

/Users/annette/Desktop/automatic_speech_recognition/project/git_folder/.venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Model loaded successfully!

In [16]:
# Prepare dataset with audio features (using torchaudio)
def prepare_dataset_manual(row):
    # Load audio using torchaudio
    waveform, sr = torchaudio.load(row["wav_path"])
    
    # Resample to 16kHz if needed
    if sr != 16000:
        resampler = torchaudio.transforms.Resample(sr, 16000)
        waveform = resampler(waveform)
    
    # Convert to mono if stereo
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0, keepdim=True)
    
    audio_array = waveform.squeeze().numpy()
    
    # Process audio
    audio_inputs = processor(audio_array, sampling_rate=16000, return_tensors="pt")
    input_values = audio_inputs["input_values"][0]
    
    # Process text
    labels = processor.tokenizer(row["transcript"])["input_ids"]
    
    return {
        "input_values": input_values.numpy().tolist(),
        "labels": labels,
        "transcript": row["transcript"]
    }

print("Preparing dataset...")
processed_data = []
skipped = []

for idx, row in df.iterrows():
    if idx % 50 == 0:
        print(f"Processing {idx}/{len(df)}...")
    try:
        processed_data.append(prepare_dataset_manual(row))
    except Exception as e:
        skipped.append((idx, row["wav_path"], str(e)))
        print(f"  Skipped {idx}: {os.path.basename(row['wav_path'])} - {e}")

print(f"\nDataset ready: {len(processed_data)} samples")
print(f"Skipped: {len(skipped)} files")

Preparing dataset...
Processing 0/270...
  Skipped 2: common_voice_sw_37772967.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37772967.wav
  Skipped 5: common_voice_sw_37990259.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37990259.wav
  Skipped 6: common_voice_sw_37803619.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37803619.wav
  Skipped 9: common_voice_sw_37840765.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37840765.wav
  Skipped 13: common_voice_sw_37916812.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37916812.wav
  Skipped 17: common_voice_sw_37806592.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37806592.wav
  Skipped 21: common_voice_sw_37397950.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37397950.wav
  Skipped 30: common_voice_sw_37663604.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663604.wav
  Skipped 31: common_voice_sw_37836026.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37836026.wav
  Skipped 34: common_voice_sw_37945295.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37945295.wav
  Skipped 38: common_voice_sw_37921397.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37921397.wav
  Skipped 45: common_voice_sw_37802855.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37802855.wav
Processing 50/270...
  Skipped 52: common_voice_sw_37860481.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37860481.wav
  Skipped 53: common_voice_sw_37860482.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37860482.wav
  Skipped 72: common_voice_sw_37916783.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37916783.wav
  Skipped 78: common_voice_sw_37663222.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663222.wav
  Skipped 79: common_voice_sw_37663417.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663417.wav
  Skipped 80: common_voice_sw_37663419.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663419.wav
  Skipped 89: common_voice_sw_37650449.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37650449.wav
  Skipped 93: common_voice_sw_37663490.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663490.wav
  Skipped 95: common_voice_sw_37663825.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663825.wav
  Skipped 96: common_voice_sw_37662836.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37662836.wav
Processing 100/270...
  Skipped 100: common_voice_sw_37663944.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663944.wav
  Skipped 113: common_voice_sw_37664050.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664050.wav
  Skipped 121: common_voice_sw_37664890.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664890.wav
  Skipped 124: common_voice_sw_37399034.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37399034.wav
  Skipped 135: common_voice_sw_37664694.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664694.wav
  Skipped 145: common_voice_sw_37664092.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664092.wav
  Skipped 148: common_voice_sw_37664208.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664208.wav
Processing 150/270...
  Skipped 155: common_voice_sw_37663636.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663636.wav
  Skipped 156: common_voice_sw_37663749.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663749.wav
  Skipped 159: common_voice_sw_37664961.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664961.wav
  Skipped 161: common_voice_sw_37665228.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37665228.wav
  Skipped 164: common_voice_sw_37329826.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37329826.wav
  Skipped 168: common_voice_sw_37331826.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37331826.wav
  Skipped 169: common_voice_sw_37331905.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37331905.wav
  Skipped 170: common_voice_sw_37331906.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37331906.wav
  Skipped 171: common_voice_sw_37331928.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37331928.wav
  Skipped 174: common_voice_sw_37331967.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37331967.wav
  Skipped 192: common_voice_sw_37665153.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37665153.wav
Processing 200/270...
  Skipped 202: common_voice_sw_37664712.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664712.wav
  Skipped 205: common_voice_sw_37664974.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664974.wav
  Skipped 206: common_voice_sw_37665089.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37665089.wav
  Skipped 213: common_voice_sw_37663337.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663337.wav
  Skipped 216: common_voice_sw_37663505.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37663505.wav
  Skipped 224: common_voice_sw_37664270.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37664270.wav
  Skipped 227: common_voice_sw_37665383.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37665383.wav
  Skipped 228: common_voice_sw_37665427.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37665427.wav
  Skipped 232: common_voice_sw_37955167.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37955167.wav
  Skipped 234: common_voice_sw_37955172.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37955172.wav
  Skipped 241: common_voice_sw_37964491.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37964491.wav
  Skipped 242: common_voice_sw_37964494.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37964494.wav
Processing 250/270...
  Skipped 250: common_voice_sw_37964530.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37964530.wav
  Skipped 251: common_voice_sw_37964544.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37964544.wav
  Skipped 254: common_voice_sw_37982153.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982153.wav
  Skipped 255: common_voice_sw_37982247.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982247.wav
  Skipped 256: common_voice_sw_37982277.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982277.wav
  Skipped 259: common_voice_sw_37982305.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982305.wav
  Skipped 262: common_voice_sw_37982359.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982359.wav
  Skipped 265: common_voice_sw_37982384.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982384.wav
  Skipped 266: common_voice_sw_37982400.wav - Error loading audio file: failed to open file /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/cleaned_sw_audio_14_0_delta/common_voice_sw_37982400.wav

Dataset ready: 209 samples
Skipped: 61 files

In [17]:
# Load evaluation metrics
wer_metric = evaluate.load('wer')
cer_metric = evaluate.load('cer')
print("Metrics loaded: WER, CER")

Downloading builder script: 5.13kB [00:00, 1.87MB/s]
Downloading builder script: 6.61kB [00:00, 3.85MB/s]

Metrics loaded: WER, CER

In [18]:
# Run inference
print("Running inference...")
predictions = []
references = []

for idx, sample in enumerate(processed_data):
    if idx % 50 == 0:
        print(f"Inferencing {idx}/{len(processed_data)}...")
    
    with torch.no_grad():
        input_values = torch.tensor(sample["input_values"]).unsqueeze(0).to(device)
        logits = model(input_values).logits
    
    pred_ids = torch.argmax(logits, dim=-1)
    pred_str = processor.batch_decode(pred_ids)[0]
    ref_str = processor.decode(sample["labels"], group_tokens=False)
    
    predictions.append(pred_str)
    references.append(ref_str)

print(f"Inference complete: {len(predictions)} samples")

Running inference...
Inferencing 0/209...
Inferencing 50/209...
Inferencing 100/209...
Inferencing 150/209...
Inferencing 200/209...
Inference complete: 209 samples

In [19]:
# Calculate WER and CER
wer_score = wer_metric.compute(predictions=predictions, references=references)
cer_score = cer_metric.compute(predictions=predictions, references=references)

print("="*50)
print("Evaluation Results")
print("="*50)
print(f"Test WER: {wer_score:.4f} ({wer_score*100:.2f}%)")
print(f"Test CER: {cer_score:.4f} ({cer_score*100:.2f}%)")
print("="*50)

==================================================
Evaluation Results
==================================================
Test WER: 1.0000 (100.00%)
Test CER: 0.9998 (99.98%)
==================================================

In [20]:
# Show sample results
from IPython.display import display, HTML
import random

results_df = pd.DataFrame({
    "reference": references,
    "prediction": predictions
})

# Show random samples
sample_indices = random.sample(range(len(results_df)), min(10, len(results_df)))
display(HTML(results_df.iloc[sample_indices].to_html()))

In [21]:
# Save results to CSV
results_df.to_csv(f"{BASE}/evaluation_results.csv", index=False)
print(f"Results saved to {BASE}/evaluation_results.csv")

Results saved to /Users/annette/Desktop/automatic_speech_recognition/project/git_folder/LR_ASR/preprocessing/processed_data/14.0-delta-2023-06-23/evaluation_results.csv